export const sidebarLinks = [
  {
    imgURL: "/icons/home.svg",
    route: "/",
    label: "Home",
  },
  {
    imgURL: "/icons/discover.svg",
    route: "/discover",
    label: "Discover",
  },
  {
    imgURL: "/icons/microphone.svg",
    route: "/create-podcast",
    label: "Create Podcast",
  },
];

// export const voiceDetails = [
//   { label: "UK English Female", value: "UK English Female" },
//   { label: "UK English Male", value: "UK English Male" },
//   { label: "US English Female", value: "US English Female" },
//   { label: "US English Male", value: "US English Male" },
//   { label: "Arabic Male", value: "Arabic Male" },
//   { label: "Arabic Female", value: "Arabic Female" },
//   { label: "Armenian Male", value: "Armenian Male" },
//   { label: "Australian Female", value: "Australian Female" },
//   { label: "Australian Male", value: "Australian Male" },
//   { label: "Bangla Bangladesh Female", value: "Bangla Bangladesh Female" },
//   { label: "Bangla Bangladesh Male", value: "Bangla Bangladesh Male" },
//   { label: "Bangla India Female", value: "Bangla India Female" },
//   { label: "Bangla India Male", value: "Bangla India Male" },
//   {
//     label: "Brazilian Portuguese Female",
//     value: "Brazilian Portuguese Female",
//   },
//   { label: "Chinese Female", value: "Chinese Female" },
//   { label: "Chinese Male", value: "Chinese Male" },
//   { label: "Chinese (Hong Kong) Female", value: "Chinese (Hong Kong) Female" },
//   { label: "Chinese (Hong Kong) Male", value: "Chinese (Hong Kong) Male" },
//   { label: "Chinese Taiwan Female", value: "Chinese Taiwan Female" },
//   { label: "Chinese Taiwan Male", value: "Chinese Taiwan Male" },
//   { label: "Czech Female", value: "Czech Female" },
//   { label: "Danish Female", value: "Danish Female" },
//   { label: "Deutsch Female", value: "Deutsch Female" },
//   { label: "Deutsch Male", value: "Deutsch Male" },
//   { label: "Dutch Female", value: "Dutch Female" },
//   { label: "Dutch Male", value: "Dutch Male" },
//   { label: "Estonian Male", value: "Estonian Male" },
//   { label: "Filipino Female", value: "Filipino Female" },
//   { label: "Finnish Female", value: "Finnish Female" },
//   { label: "French Female", value: "French Female" },
//   { label: "French Male", value: "French Male" },
//   { label: "French Canadian Female", value: "French Canadian Female" },
//   { label: "French Canadian Male", value: "French Canadian Male" },
//   { label: "Greek Female", value: "Greek Female" },
//   { label: "Hindi Female", value: "Hindi Female" },
//   { label: "Hindi Male", value: "Hindi Male" },
//   { label: "Hungarian Female", value: "Hungarian Female" },
//   { label: "Indonesian Female", value: "Indonesian Female" },
//   { label: "Indonesian Male", value: "Indonesian Male" },
//   { label: "Italian Female", value: "Italian Female" },
//   { label: "Italian Male", value: "Italian Male" },
//   { label: "Japanese Female", value: "Japanese Female" },
//   { label: "Japanese Male", value: "Japanese Male" },
//   { label: "Korean Female", value: "Korean Female" },
//   { label: "Korean Male", value: "Korean Male" },
//   { label: "Latin Male", value: "Latin Male" },
//   { label: "Nepali", value: "Nepali" },
//   { label: "Norwegian Female", value: "Norwegian Female" },
//   { label: "Norwegian Male", value: "Norwegian Male" },
//   { label: "Polish Female", value: "Polish Female" },
//   { label: "Polish Male", value: "Polish Male" },
//   { label: "Portuguese Female", value: "Portuguese Female" },
//   { label: "Portuguese Male", value: "Portuguese Male" },
//   { label: "Romanian Female", value: "Romanian Female" },
//   { label: "Russian Female", value: "Russian Female" },
//   { label: "Sinhala", value: "Sinhala" },
//   { label: "Slovak Female", value: "Slovak Female" },
//   { label: "Spanish Female", value: "Spanish Female" },
//   {
//     label: "Spanish Latin American Female",
//     value: "Spanish Latin American Female",
//   },
//   {
//     label: "Spanish Latin American Male",
//     value: "Spanish Latin American Male",
//   },
//   { label: "Swedish Female", value: "Swedish Female" },
//   { label: "Swedish Male", value: "Swedish Male" },
//   { label: "Tamil Female", value: "Tamil Female" },
//   { label: "Tamil Male", value: "Tamil Male" },
//   { label: "Thai Female", value: "Thai Female" },
//   { label: "Thai Male", value: "Thai Male" },
//   { label: "Turkish Female", value: "Turkish Female" },
//   { label: "Turkish Male", value: "Turkish Male" },
//   { label: "Ukrainian Female", value: "Ukrainian Female" },
//   { label: "Vietnamese Female", value: "Vietnamese Female" },
//   { label: "Vietnamese Male", value: "Vietnamese Male" },
//   { label: "Afrikaans Male", value: "Afrikaans Male" },
//   { label: "Albanian Male", value: "Albanian Male" },
//   { label: "Bosnian Male", value: "Bosnian Male" },
//   { label: "Catalan Male", value: "Catalan Male" },
//   { label: "Croatian Male", value: "Croatian Male" },
//   { label: "Esperanto Male", value: "Esperanto Male" },
//   { label: "Icelandic Female", value: "Icelandic Female" },
//   { label: "Latvian Male", value: "Latvian Male" },
//   { label: "Macedonian Male", value: "Macedonian Male" },
//   { label: "Moldavian Female", value: "Moldavian Female" },
//   { label: "Montenegrin Male", value: "Montenegrin Male" },
//   { label: "Serbian Male", value: "Serbian Male" },
//   { label: "Serbo-Croatian Male", value: "Serbo-Croatian Male" },
//   { label: "Swahili Male", value: "Swahili Male" },
//   { label: "Welsh Male", value: "Welsh Male" },
//   { label: "Fallback UK Female", value: "Fallback UK Female" },
// ];

export const podcastData = [
  {
    id: 1,
    title: "The Joe Rogan Experience",
    description: "A long form, in-depth conversation",
    imgURL:
      "https://lovely-flamingo-139.convex.cloud/api/storage/3106b884-548d-4ba0-a179-785901f69806",
  },
  {
    id: 2,
    title: "The Futur",
    description: "This is how the news should sound",
    imgURL:
      "https://lovely-flamingo-139.convex.cloud/api/storage/16fbf9bd-d800-42bc-ac95-d5a586447bf6",
  },
  {
    id: 3,
    title: "Waveform",
    description: "Join Michelle Obama in conversation",
    imgURL:
      "https://lovely-flamingo-139.convex.cloud/api/storage/60f0c1d9-f2ac-4a96-9178-f01d78fa3733",
  },
  {
    id: 4,
    title: "The Tech Talks Daily Podcast",
    description: "This is how the news should sound",
    imgURL:
      "https://lovely-flamingo-139.convex.cloud/api/storage/5ba7ed1b-88b4-4c32-8d71-270f1c502445",
  },
  {
    id: 5,
    title: "GaryVee Audio Experience",
    description: "A long form, in-depth conversation",
    imgURL:
      "https://lovely-flamingo-139.convex.cloud/api/storage/ca7cb1a6-4919-4b2c-a73e-279a79ac6d23",
  },
  {
    id: 6,
    title: "Syntax ",
    description: "Join Michelle Obama in conversation",
    imgURL:
      "https://lovely-flamingo-139.convex.cloud/api/storage/b8ea40c7-aafb-401a-9129-73c515a73ab5",
  },
  {
    id: 7,
    title: "IMPAULSIVE",
    description: "A long form, in-depth conversation",
    imgURL:
      "https://lovely-flamingo-139.convex.cloud/api/storage/8a55d662-fe3f-4bcf-b78b-3b2f3d3def5c",
  },
  {
    id: 8,
    title: "Ted Tech",
    description: "This is how the news should sound",
    imgURL:
      "https://lovely-flamingo-139.convex.cloud/api/storage/221ee4bd-435f-42c3-8e98-4a001e0d806e",
  },
];

export const episodesData = [
  {
    episode: "1",
    title: "The Joe Rogan Experience",
    description: "A long form, in-depth conversation",
  },
  {
    episode: "2",
    title: "The Futur",
    description: "This is how the news should sound",
  },
  {
    episode: "3",
    title: "Waveform",
    description: "Join Michelle Obama in conversation",
  },
  {
    episode: "4",
    title: "The Tech Talks Daily Podcast",
    description: "This is how the news should sound",
  },
  {
    episode: "5",
    title: "GaryVee Audio Experience",
    description: "A long form, in-depth conversation",
  },
  {
    episode: "6",
    title: "Syntax ",
    description: "Join Michelle Obama in conversation",
  },
  {
    episode: "7",
    title: "IMPAULSIVE",
    description: "A long form, in-depth conversation",
  },
  {
    episode: "8",
    title: "Ted Tech",
    description: "This is how the news should sound",
  },
];
